version: "3.8"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    networks:
      - llm
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:3000
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:0.3.10
    networks:
      - llm
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REACT_APP_API_URL= http://localhost:8000
    depends_on:
      - backend

networks:
  llm:
    driver: bridge