version: "3.8"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    depends_on:
      - backend